template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-9fcc09f7
  VpcPrivateRouteTable: rtb-0093237c
  VpcPublicRouteTable: rtb-f0aa1a8c
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-route-config.yaml --create-dirs -o remote-templates/peer-route-config.yaml"
